trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-az-pipelines-yaml-shared - RELEASE - DEV'
  
variables:
  vmImageName: 'vs2017-win2016'
  azureSubscription: 'Rutz Internal Demo Account (164a84cf-b099-4567-a527-c2a8143a32c7)'

stages:
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: 'PROD'
    environment: 'API-PROD'
    azureSubscription: ${{ variables.azureSubscription }}
    functionAppName: 'demo-function-api-prod'
    resourceGroupName: 'demo-function-api-prod'
    storageAccountName: 'azfunctdapiprod'
    region: 'Central US'
    packageName: 'Demo.Function.API.zip'
