trigger:
- main

resources:
  repositories:
  - repository: App 
    type: github
    endpoint: rutzsco
    name: rutzsco/demo-az-pipelines-yaml-app
    trigger:
      branches:
        include:
        - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Infrastructure'
  inputs:
    PathtoPublish: Infrastructure
    ArtifactName: Infrastructure
